### ISSUE TITLE
Question: Why multiple endpoints

### ISSUE THREAD

**Issue by hkusulja** [frankchen76/EZCode-Adal-Angular5-Sample#1]
In ezcodeAdalConfigLocal, why endpoints is object array? When Azure AD does not giving the token granting the multiple endpoints. It should be individual token for each endpoint.

**Comment by frankchen76** [comment]
the logic inside http interceptor (ezcode-http.interceptor.ts) will get token based on the endpoints you defined there.  So from caller perspective, you just simply call HttpClient.get() to get the result as long as you defined your endpoint(api url and resource id) in the config. the library will handle the token acquiring process for you. Does it make sense?

**Comment by hkusulja** [comment]
@frankchen76 yes, thank you very much
