### ISSUE TITLE
Missing File

### ISSUE THREAD

**Issue by BgRva** [frankchen76/EZCode-Adal-Angular5-Sample#2]
I get the following error when I run the example:

ERROR in src/app/app.module.ts(20,39): error TS2307: Cannot find module './services/ezcodeAdalConfig.local'.

**Comment by frankchen76** [comment]
@BgRva , sorry for late response. when you look at project home page, you will find out I mentioned you need to create that file (ezcodeadalConfig.local.ts) to contain your AAD connection information. please see below. Sorry I think I should change from ezcodeadalconfig.ts to ezcodeadalconfig.local.ts. 

> Create a adal configuration file **_ezcodeadalconfig.local.ts_** under service folder and update your tenant id, clientId to your Azure AD App configuration. If you want to call 3rd party API secured by Azure AD, make sure you enter the correct Web API url and Resource Id.
> import {IEZCodeAdalConfig} from 'ezcode-adal-angular5/lib/IEZCodeAdalConfig';
> 
> export const ezcodeAdalConfigLocal: IEZCodeAdalConfig={
>     tenant: '[your tenant name/id]',
>     clientId: '[your client id]',
>     redirectUri: window.location.href.substring(0, window.location.href.lastIndexOf("/")+1), 
>     postLogoutRedirectUri: window.location.origin + '/',
>     endpoints: {
>         'https://graph.microsoft.com/v1.0/me': 'https://graph.microsoft.com',
>         '[webapi url]': '[webapi resource id]'
> 
>     }
> };
> 

Thanks and let me know if that helps.
